### ISSUE TITLE
Device shows 100% battery when in fact it has 0%

### ISSUE THREAD

**Issue by danielkucera** [bosmoment/PineTime-apps#13]
See attached picture
![IMG_20200130_175923](https://user-images.githubusercontent.com/1734256/73472279-1597b380-438b-11ea-8822-a8fc6ade13e3.jpg)

**Comment by danielkucera** [comment]
moreover the voltage/percentage ratio is not constant:
https://lygte-info.dk/info/BatteryChargePercent%20UK.html

**Comment by bergzand** [comment]
@danielkucera I assume we can close this now that #14 is merged?

Thanks for reporting and providing a fix
