### ISSUE TITLE
Heartrate mesurment

### ISSUE THREAD

**Issue by luben93** [bosmoment/PineTime-apps#17]
when trying with both gadgetbridge https://github.com/luben93/Gadgetbridge/tree/riotwatch/heartrate and nRF connect i dont get any response while subscribing on 0x2A37 (Heart Rate Measurement), and i suspect this line https://github.com/bosmoment/PineTime-apps/blob/master/modules/bleman/bleman.c#L146 as the culprite here, could we start sending a hardcoded value until we can read from the sensor?

**Comment by bergzand** [comment]
> could we start sending a hardcoded value until we can read from the sensor?

Would something similar to [this example](https://github.com/RIOT-OS/RIOT/tree/master/examples/nimble_heart_rate_sensor) be okay?

**Comment by luben93** [comment]
seems fine

**Comment by bergzand** [comment]
Done, the current code should provide a new value every second between `BLEMAN_HRS_FAKE_MIN` and `BLEMAN_HRS_FAKE_MAX`
