### ISSUE TITLE
documentation: add riot-os tag

### ISSUE THREAD

**Issue by fjmolinas** [bosmoment/PineTime-apps#22]
Hi! Really cool project, I was looking for RIOT examples and it took me while to find this, I think it could be more visible if tags like `riot-os`, `riot`, etc.. where added to the project! Cheers!

**Comment by fjmolinas** [comment]
@bergzand might be the right person to handle this?

**Comment by bergzand** [comment]
Done, thanks for the suggestion!

**Comment by fjmolinas** [comment]
Wow quick response!
